services:
  mysql:
    image: mysql:8.0
    container_name: mysql_server_annuaire
    environment:
      MYSQL_ROOT_PASSWORD: qwerty
      MYSQL_DATABASE: annuaire
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  mysql_data:
